# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anaekran_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AnaEkran(object):
    def setupUi(self, AnaEkran):
        AnaEkran.setObjectName("AnaEkran")
        AnaEkran.resize(800, 600)
        self.AnaForm = QtWidgets.QWidget(AnaEkran)
        self.AnaForm.setObjectName("AnaForm")
        self.tableWidget = QtWidgets.QTableWidget(self.AnaForm)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 791, 561))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        AnaEkran.setCentralWidget(self.AnaForm)
        self.menubar = QtWidgets.QMenuBar(AnaEkran)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        self.menuKitap_Listesi = QtWidgets.QMenu(self.menubar)
        self.menuKitap_Listesi.setObjectName("menuKitap_Listesi")
        self.menuKitap_Ekle = QtWidgets.QMenu(self.menubar)
        self.menuKitap_Ekle.setObjectName("menuKitap_Ekle")
        self.menuKitap_Guncelle = QtWidgets.QMenu(self.menubar)
        self.menuKitap_Guncelle.setObjectName("menuKitap_Guncelle")
        self.menuKitap_Sil = QtWidgets.QMenu(self.menubar)
        self.menuKitap_Sil.setObjectName("menuKitap_Sil")
        self.menu_cikis = QtWidgets.QMenu(self.menubar)
        self.menu_cikis.setObjectName("menu_cikis")
        AnaEkran.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AnaEkran)
        self.statusbar.setObjectName("statusbar")
        AnaEkran.setStatusBar(self.statusbar)
        self.actionKitap_Ekleme = QtWidgets.QAction(AnaEkran)
        self.actionKitap_Ekleme.setObjectName("actionKitap_Ekleme")
        self.actionKitap_Listeleme = QtWidgets.QAction(AnaEkran)
        self.actionKitap_Listeleme.setObjectName("actionKitap_Listeleme")
        self.actionKitap_Guncelleme = QtWidgets.QAction(AnaEkran)
        self.actionKitap_Guncelleme.setObjectName("actionKitap_Guncelleme")
        self.actionKitap_Silme = QtWidgets.QAction(AnaEkran)
        self.actionKitap_Silme.setObjectName("actionKitap_Silme")
        self.action_cikis = QtWidgets.QAction(AnaEkran)
        self.action_cikis.setObjectName("action_cikis")
        self.menuKitap_Listesi.addAction(self.actionKitap_Listeleme)
        self.menuKitap_Ekle.addAction(self.actionKitap_Ekleme)
        self.menuKitap_Guncelle.addAction(self.actionKitap_Guncelleme)
        self.menuKitap_Sil.addAction(self.actionKitap_Silme)
        self.menubar.addAction(self.menuKitap_Listesi.menuAction())
        self.menubar.addAction(self.menuKitap_Ekle.menuAction())
        self.menubar.addAction(self.menuKitap_Guncelle.menuAction())
        self.menubar.addAction(self.menuKitap_Sil.menuAction())
        self.menubar.addAction(self.menu_cikis.menuAction())

        self.retranslateUi(AnaEkran)
        QtCore.QMetaObject.connectSlotsByName(AnaEkran)

    def retranslateUi(self, AnaEkran):
        _translate = QtCore.QCoreApplication.translate
        AnaEkran.setWindowTitle(_translate("AnaEkran", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("AnaEkran", "Kitap_ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("AnaEkran", "Kitap Adı"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("AnaEkran", "Kitap Yazarı"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("AnaEkran", "Kitap Okunma Durumu"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("AnaEkran", "Kitap Beğeni Durumu"))
        self.menuKitap_Listesi.setTitle(_translate("AnaEkran", "Kitap Listesi"))
        self.menuKitap_Ekle.setTitle(_translate("AnaEkran", "Kitap Ekle"))
        self.menuKitap_Guncelle.setTitle(_translate("AnaEkran", "Kitap Güncelle"))
        self.menuKitap_Sil.setTitle(_translate("AnaEkran", "Kitap Sil"))
        self.menu_cikis.setTitle(_translate("AnaEkran", "Çıkış"))
        self.actionKitap_Ekleme.setText(_translate("AnaEkran", "Kitap Ekleme"))
        self.actionKitap_Listeleme.setText(_translate("AnaEkran", "Kitap Listeleme"))
        self.actionKitap_Guncelleme.setText(_translate("AnaEkran", "Kitap Güncelleme"))
        self.actionKitap_Silme.setText(_translate("AnaEkran", "Kitap Silme"))
        self.action_cikis.setText(_translate("AnaEkran", "Çıkış"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AnaEkran = QtWidgets.QMainWindow()
    ui = Ui_AnaEkran()
    ui.setupUi(AnaEkran)
    AnaEkran.show()
    sys.exit(app.exec_())
