# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'giris.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(44, 70, 51, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(44, 100, 51, 20))
        self.label_2.setObjectName("label_2")
        self.mesajLabel = QtWidgets.QLabel(Form)
        self.mesajLabel.setGeometry(QtCore.QRect(100, 200, 131, 30))
        self.mesajLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.mesajLabel.setObjectName("mesajLabel")
        self.girisButton = QtWidgets.QPushButton(Form)
        self.girisButton.setGeometry(QtCore.QRect(130, 150, 87, 35))
        self.girisButton.setObjectName("girisButton")
        self.epostaText = QtWidgets.QLineEdit(Form)
        self.epostaText.setGeometry(QtCore.QRect(100, 70, 113, 20))
        self.epostaText.setObjectName("epostaText")
        self.sifreText = QtWidgets.QLineEdit(Form)
        self.sifreText.setGeometry(QtCore.QRect(100, 110, 113, 20))
        self.sifreText.setObjectName("sifreText")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Eposta:"))
        self.label_2.setText(_translate("Form", "Şifre:"))
        self.mesajLabel.setText(_translate("Form", "Mesaj"))
        self.girisButton.setText(_translate("Form", "Giriş "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
