# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kitapekle.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KitapEkleForm(object):
    def setupUi(self, KitapEkleForm):
        KitapEkleForm.setObjectName("KitapEkleForm")
        KitapEkleForm.resize(400, 300)
        self.formLayoutWidget = QtWidgets.QWidget(KitapEkleForm)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 40, 361, 111))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.kitap_AdiLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.kitap_AdiLabel.setObjectName("kitap_AdiLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.kitap_AdiLabel)
        self.kitap_Adi = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.kitap_Adi.setObjectName("kitap_Adi")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.kitap_Adi)
        self.kitap_YazariLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.kitap_YazariLabel.setObjectName("kitap_YazariLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.kitap_YazariLabel)
        self.kitap_YazariLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.kitap_YazariLineEdit.setObjectName("kitap_YazariLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.kitap_YazariLineEdit)
        self.okunma_DurumuLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.okunma_DurumuLabel.setObjectName("okunma_DurumuLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.okunma_DurumuLabel)
        self.okunma_DurumuCheckBox = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.okunma_DurumuCheckBox.setObjectName("okunma_DurumuCheckBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.okunma_DurumuCheckBox)
        self.begeni_DurumuLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.begeni_DurumuLabel.setObjectName("begeni_DurumuLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.begeni_DurumuLabel)
        self.begeni_DurumuComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.begeni_DurumuComboBox.setObjectName("begeni_DurumuComboBox")
        self.begeni_DurumuComboBox.addItem("")
        self.begeni_DurumuComboBox.addItem("")
        self.begeni_DurumuComboBox.addItem("")
        self.begeni_DurumuComboBox.addItem("")
        self.begeni_DurumuComboBox.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.begeni_DurumuComboBox)
        self.kayit_durum = QtWidgets.QLabel(KitapEkleForm)
        self.kayit_durum.setGeometry(QtCore.QRect(30, 170, 351, 31))
        self.kayit_durum.setObjectName("kayit_durum")
        self.kaydetButton = QtWidgets.QPushButton(KitapEkleForm)
        self.kaydetButton.setGeometry(QtCore.QRect(90, 230, 201, 31))
        self.kaydetButton.setObjectName("kaydetButton")

        self.retranslateUi(KitapEkleForm)
        QtCore.QMetaObject.connectSlotsByName(KitapEkleForm)

    def retranslateUi(self, KitapEkleForm):
        _translate = QtCore.QCoreApplication.translate
        KitapEkleForm.setWindowTitle(_translate("KitapEkleForm", "Form"))
        self.kitap_AdiLabel.setText(_translate("KitapEkleForm", "Kitap_Adi"))
        self.kitap_YazariLabel.setText(_translate("KitapEkleForm", "Kitap_Yazari"))
        self.okunma_DurumuLabel.setText(_translate("KitapEkleForm", "Okunma_Durumu"))
        self.begeni_DurumuLabel.setText(_translate("KitapEkleForm", "Begeni_Durumu"))
        self.begeni_DurumuComboBox.setItemText(0, _translate("KitapEkleForm", "1"))
        self.begeni_DurumuComboBox.setItemText(1, _translate("KitapEkleForm", "2"))
        self.begeni_DurumuComboBox.setItemText(2, _translate("KitapEkleForm", "3"))
        self.begeni_DurumuComboBox.setItemText(3, _translate("KitapEkleForm", "4"))
        self.begeni_DurumuComboBox.setItemText(4, _translate("KitapEkleForm", "5"))
        self.kayit_durum.setText(_translate("KitapEkleForm", "Kayıt Durumu:"))
        self.kaydetButton.setText(_translate("KitapEkleForm", "Kitap Kaydet"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    KitapEkleForm = QtWidgets.QWidget()
    ui = Ui_KitapEkleForm()
    ui.setupUi(KitapEkleForm)
    KitapEkleForm.show()
    sys.exit(app.exec_())
